# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: mp-lvgl-example

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: micropython
      url-base: https://github.com/micropython
    - name: lvgl
      url-base: https://github.com/lvgl
    - name: marble
      url-base: https://github.com/cyber-murmel

  projects:
    - name: zephyr
      remote: marble
      revision: 151046a633fbf08c2878e1c5f2be9227bc553abd
      path: modules/zephyr
      import:
        name-allowlist:
          - hal_espressif
          - mcuboot
          - fatfs
          - lvgl
    - name: micropython
      remote: micropython
      revision: 9faaa837f47efe76b57e337e5d30e07fcd10be1a
      path: modules/micropython
    - name: lv_binding_micropython
      remote: marble
      revision: mp-lvgl
      path: modules/lib/gui/lv_binding_micropython
      import:
        name-allowlist:
          - pycparser
    - name: micropython-lib
      remote: micropython
      revision: v1.29.0
      path: modules/micropython/lib/micropython-lib
