CONFIG_BUILD_OUTPUT_BIN=y
CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_OUTPUT_DISASSEMBLY=y

CONFIG_DEVICE_DT_METADATA=y

CONFIG_LEGACY_GENERATED_INCLUDE_PATH=n

# CONFIG_DYNAMIC_THREAD=y

# MicroPython options
CONFIG_MICROPY_CONFIGFILE="mpconfigport_zephyr_lvgl.h"
CONFIG_MICROPY_FROZEN_MODULES=y
CONFIG_MICROPY_CONFIG_ROM_LEVEL_EVERYTHING=y

CONFIG_LVGL=y
CONFIG_LV_COLOR_16_SWAP=y
CONFIG_LV_Z_MEM_POOL_MICROPYTHON=y
CONFIG_LV_Z_AUTO_INIT=n
CONFIG_LV_USE_FILE_EXPLORER=y

# # Diagnostics and debugging

# Required for zephyr.stack_analyze()
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_LOG=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_CUSTOM_DATA=y

# Networking config
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_INIT_TIMEOUT=3
CONFIG_NET_CONFIG_NEED_IPV6=y
CONFIG_NET_CONFIG_NEED_IPV4=y

# DNS
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_RESOLVER_ADDITIONAL_QUERIES=2
CONFIG_DNS_SERVER_IP_ADDRESSES=y

# Static IP addresses
CONFIG_NET_CONFIG_MY_IPV6_ADDR="2001:db8::1"
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_CONFIG_MY_IPV4_GW="192.0.2.2"
CONFIG_DNS_SERVER1="192.0.2.2"

# DHCP configuration. Until DHCP address is assigned,
# static configuration above is used instead.
CONFIG_NET_DHCPV4=y

# Required for socket.pkt_get_info()
CONFIG_NET_BUF_POOL_USAGE=y

CONFIG_WATCHDOG=y
CONFIG_WDT_DISABLE_AT_BOOT=y
